config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/converter'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'records#index'

  resources :regions do
    resources :rocks do
      resources :zones do
        resources :areas do
          resources :routes
        end
      end
    end
  end

  resources :regions, only: :index do
    collection { post :import }
  end

  resources :rocks, only: :index do
    collection { post :import }
  end

  resources :zones, only: :index do
    collection { post :import }
  end

  resources :areas, only: :index do
    collection { post :import }
  end

  resources :records do
    collection do
      get :rocks_select
      get :areas_select
      get :routes_select
    end
  end

  resources :routes do
    collection do
      get :areas_select
    end
  end

  resources :routes, only: :index do
    collection { post :import }
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :records
  resources :users
  resources :rocks
  resources :areas
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  get '/signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :records, dependent: :destroy
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true
  validates :user_name, presence: true, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 与えられた文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # アカウントに管理権限を持たせる(rails consoleでの使用に限定)
  def enrich_admin
    update_attribute(:admin,    true)
  end

  # アカウントから管理権限を剥奪する(rails consoleでの使用に限定)
  def deprive_admin
    update_attribute(:admin,    false)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes({:records => :rock}, {:records => :area}, {:records => :route}).find(params[:id])
    @records = @user.records.order("records.day DESC").page(params[:page])
    @grades = Record.joins(:route).where(user_id: params[:id]).group("records.result, routes.grade").order("routes.grade").pluck("routes.grade, records.result, count('id')")
    @lines = @grades.group_by{ |grade| grade[0] }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Sent confirmation mail. Finish registration with click the link."
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :user_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_records.html.erb
<%= page_entries_info @records %>

<table class="table table-striped table-hover">
  <tbody>
  <% @records.each do |rec| %>
    <tr>
      <td class="col-md-2"><%= rec.day %></td>
<%
begin
  area_name = rec.area.name
rescue
  area_name = ""
end

begin
  route_name = rec.route.name
  route_grade = rec.route.grade
rescue
  route_name = ""
  route_grade = ""
end

result_span =
  case rec.result
  when "Onsight"
    "primary"
  when "Flash"
    "info"
  when "Send"
    "success"
  when "Project"
    "default"
  end
%>
      <td class="col-md-9"><%= link_to "#{rec.rock.name} / #{area_name} / #{route_name}(#{route_grade})", record_path(rec.id) %></td>
      <td class="col-md-1"><span class="label label-<%= result_span %>"><%= rec.result %></span></td>
    </tr>
  <% end %>
  </tbody>
  <p><%= "You have #{@records.count} records." %></p>
</table>

<div class="col-md12">
  <%= paginate @records %>
</div>

app/views/users/_records_grades.html.erb
<ul class="list-group">
  <% @lines.each do |line|
    grade = line[0]
    set = line[1]
  %>
    <li class="list-group-item">
      <%= grade %><br><hr>
      <% set.each do |se| %>
      <div class="col-md-offset-1">
        <% se.each_with_index do |s, i| %>
          <% if i == 1 %>
            <%= s %>
          <% elsif i == 2 %>
            <a href="#"><span class="badge"><%= s %></span></a><br>
          <% end %>
        <% end %>
      </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= link_to user.user_name, user_path(user.id) %> <%= user.name %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Register</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <%= form_for @user, html: {class: 'form-horizontal'} do |u| %>
    <%= render 'shared/error_messages' %>

    <div class="form-group">
      <%= u.label :name, "Name", class: 'col-sm-3 control-label' %>
      <div class="col-md-7">
        <%= u.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= u.label :user_name, "User name", class: 'col-sm-3 control-label' %>
      <div class="col-md-7">
        <%= u.text_field :user_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= u.label :email, "E-mail", class: 'col-sm-3 control-label' %>
      <div class="col-md-7">
        <%= u.text_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= u.label :password, "Password", class: 'col-sm-3 control-label' %>
      <div class="col-md-7">
        <%= u.password_field :password, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= u.label :password_confirmation, "Password(confirmation)", class: 'col-sm-3 control-label' %>
      <div class="col-md-7">
        <%= u.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= u.submit "Submit", class: "btn btn-primary btn-lg" %>
    </div>

  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3><%= @user.user_name %></h3>

<button class="btn btn-danger">
<%= link_to "Logout", logout_path, method: :delete, style: "color: white" %>
</button>
<% if current_user.admin? %>
<div class="btn-group dropup">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    <i class="fas fa-cog fa-lg"></i>
  </button>
  <div class="dropdown-menu">
    <%= link_to "Region master", regions_path, class: "dropdown-item", style: "color: black" %>
    <%= link_to "Rock master", rocks_path, class: "dropdown-item", style: "color: black" %>
    <%= link_to "Area master", areas_path, class: "dropdown-item", style: "color: black" %>
    <%= link_to "Route master", routes_path, class: "dropdown-item", style: "color: black" %>
    <div class="dropdown-divider"></div>
    <%= link_to "User master", users_path, class: "dropdown-item", style: "color: black" %>
  </div>
</div>
<% end %>

<ul class="nav nav-tabs">
  <li class="active"><%= link_to 'All records', "#all_records", data: {toggle: 'tab'} %></li>
  <li><%= link_to 'Grouped by grades', "#grades", data: {toggle: 'tab'} %></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="all_records">
    <%= render 'users/records' %>
  </div>
  <div class="tab-pane" id="grades">
    <%= render 'users/records_grades' %>
  </div>
</div>