config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/converter'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'records#index'

  resources :regions do
    resources :rocks do
      resources :zones do
        resources :areas do
          resources :routes
        end
      end
    end
  end

  resources :regions, only: :index do
    collection { post :import }
  end

  resources :rocks, only: :index do
    collection { post :import }
  end

  resources :zones, only: :index do
    collection { post :import }
  end

  resources :areas, only: :index do
    collection { post :import }
  end

  resources :records do
    collection do
      get :rocks_select
      get :areas_select
      get :routes_select
    end
  end

  resources :routes do
    collection do
      get :areas_select
    end
  end

  resources :routes, only: :index do
    collection { post :import }
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :records
  resources :users
  resources :rocks
  resources :areas
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  get '/signup' => 'users#new'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :rock
  belongs_to :area
  belongs_to :route
  belongs_to :user

  mount_uploader :picture, PictureUploader

  validates :rock_id, presence: true
  validates :area_id, presence: true
  validates :route_id, presence: true
  validates :result, presence: true
  validates :day, presence: true
  validate  :picture_size

  scope :search_some_cols, lambda { |word|
    if word.blank?
      Record.all
    else
      search_word = word.downcase
      Record.joins(:rock, :area, :route, :user)
      .where(
        "lower(rocks.name) LIKE '%" + search_word + "%' or
        lower(areas.name) LIKE '%" + search_word + "%' or
        lower(routes.name) LIKE '%" + search_word + "%' or
        lower(routes.grade) LIKE '%" + search_word + "%' or
        lower(users.user_name) LIKE '%" + search_word + "%'"
        )
    end
  }

  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update]

  def index
    @records = Record
    .includes(:user, :area, :route, :rock)
    .search_some_cols(params[:search])
    .order("id DESC")
    .page(params[:page])
  end

  def show
  end

  def new
    @record = Record.new
    # rock_id = Area.find(params[:area_id]).rock_id
    # @record.rock_id = rock_id
    # @record.area_id = params[:area_id]
    # @record.route_id = params[:route_id]
    # @region_id = Rock.find(rock_id).region_id
  end

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      redirect_to records_path
    else
      render 'new'
    end
  end

  def edit
    @regions_select = Region.select("id, name")
  end

  def update
    if @record.update(record_params)
      redirect_to record_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
  end

  def rocks_select
    if request.xhr?
      render partial: 'rocks', locals: {kind: params[:kind], region_id: params[:region_id]}
    end
  end

  def areas_select
    if request.xhr?
      render partial: 'areas', locals: {rock_id: params[:rock_id]}
    end
  end

  def routes_select
    if request.xhr?
      render partial: 'routes', locals: {area_id: params[:area_id]}
    end
  end

  private

    def record_params
      params[:record].permit(:rock_id, :area_id, :route_id, :grade, :day, :result, :memo, :picture)
    end

    def set_record
      @record = Record.find(params[:id])
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_areas.html.erb
<%=
  collection_select(
    :record,
    :area_id,
    Area.where(rock_id: rock_id),
    :id,
    :name,
    {include_blank: 'Select area'}, 
    {class: "form-control"}
  )
%>

app/views/records/_form.html.erb
<div class="col-md-12 col-sm-12">
  <%= form_for @record, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group" id="record_kind_box">
      <%= f.label "Type", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-8 col-sm-8">
        <label class="radio-inline">
          <% params[:kind] == '0' ? checked = {:checked => true} : checked = nil %>
          <%= radio_button_tag :kind, 0, checked %>Sport
        </label>
        <label class="radio-inline">
          <% params[:kind] == '1' ? checked = {:checked => true} : checked = nil %>
          <%= radio_button_tag :kind, 1, checked %>Boulder
        </label>
        <label class="radio-inline">
          <% params[:kind] == '2' ? checked = {:checked => true} : checked = nil %>
          <%= radio_button_tag :kind, 2, checked %>Crack
        </label>
        <label class="radio-inline">
          <% params[:kind] == '3' ? checked = {:checked => true} : checked = nil %>
          <%= radio_button_tag :kind, 3, checked %>Trad
        </label>
      </div>
    </div>

    <div class="form-group" id="record_region_box" style="display:none">
      <%= f.label "Route", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-11 col-sm-11" id="record_region">
        <%=
          collection_select(
            :region,
            :id,
            Region.where(able: true),
            :id,
            :name,
            {selected: @region_id},
            class: "form-control"
          )
        %>
      </div>
    </div>

    <div class="form-group" id="record_rock_box" style="display:none">
      <%= f.label " ", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-11 col-sm-11" id="record_rock">
        <%= f.collection_select( :rock_id, Rock.all, :id, :name, {include_blank: 'Select rock'}, {class: "form-control"} ) %>
      </div>
    </div>

    <div class="form-group" id="record_area_box" style="display:none">
      <%= f.label " ", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-11 col-sm-11" id="areas_select">
      <%= render partial: 'areas', locals: {rock_id:
      begin
        @record.rock_id
      rescue
        Rock.first.id
      end
      } %>
      </div>
    </div>

    <div class="form-group" id="record_route_box" style="display:none">
      <%= f.label " ", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-11 col-sm-11" id="routes_select">
        <%= render partial: 'routes', locals: {area_id:
        begin
          @record.area_id
        rescue
          Area.first.id
        end
        } %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Date", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-3 col-sm-3">
        <%= f.date_field :day, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Result", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-3 col-sm-3">
        <%= f.select :result, ['Onsight', 'Flash', 'Send', 'Project'], {include_blank: 'Select result'}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Comment", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-11 col-sm-11">
        <%= f.text_area :memo, {class: 'form-control', rows: 6} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Image", class: 'col-md-1 col-sm-1' %>
      <div class="col-md-3 col-sm-3 picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    </div>

    <div class="form-group">
      <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
        <%= f.submit "Update", class: 'btn btn-primary btn-block' %>
      </div>
    </div>

  <% end %>
</div>

<script type="text/javascript">
$('#record_picture').bind('change', function() {
  var size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 5) {
    alert('Maximum file size is 5MB. Please choose a smaller file.');
  }
});
</script>

app/views/records/_rocks.html.erb
<%=
  collection_select(
    :record,
    :rock_id,
    Rock.joins(:areas => :routes).where("routes.kind = ? and rocks.region_id = ?", kind, region_id).uniq,
    :id,
    :name,
    {include_blank: 'Select rock'},
    {class: "form-control"}
  )
%>

app/views/records/_routes.html.erb
<%=
  collection_select(
    :record,
    :route_id,
    Route.where(area_id: area_id),
    :id,
    :route_name_and_grade,
    {include_blank: 'Select route'},
    {class: "form-control"}
  )
%>

app/views/records/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3><%= "#{@record.route.name} (#{@record.route.grade}) (Editing)" %></h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/records/index.html.erb
<!--
<div class="container side-bar col-md-3 col-sm-3">
  <%= render "regions/search" %>
</div>

<div class="col-md-12 col-sm-12">
  <div class="col-md-7 col-sm-7">
    <h3>Records  <small><%= page_entries_info @records %></small></h3>
  </div>

  <div class="col-md-5 col-sm-5">
    <%= form_tag records_path, {method: "get", class: "navbar-form navbar-left", role: "search"} do %>
      <div class="form-group">
        <%= text_field_tag :search, params[:search], {class: 'form-control', placeholder: 'Route/Probrem'} %>
      </div>
      <%= submit_tag "Search", {:name => nil, class: 'btn btn-default'} %>
    <% end %>
  </div>
-->
  <table class="col-12 table">
    <tbody>
    <% @records.each do |rec| %>
      <tr><td class="post">
          <div class="col-12 post">
            <div class="row align-items-center">
              <div class="col-12 clearfix">
                <b class="uname"><%= link_to rec.user.user_name, user_path(rec.user_id) %></b>
                <button class="btn float-right"><i class="fas fa-ellipsis-v"></i></button>
              </div>
            </div>
            <div class="row">
              <div class="col-md-4 col-12 pict">
              <% if rec.picture? %>
              <%= image_tag(rec.picture.url, :class => "img-fluid") %></div>
              <% else %>
              <p class="no-img-thumbnail">No<br>Image</p></div>
              <% end %>
                <div class="col desc-box">
                  <div class="date"><p><%= rec.day %></p></div>
<%
begin
  area_name = rec.area.name
rescue
  area_name = ""
end

begin
  route_name = rec.route.name
  route_grade = rec.route.grade
rescue
  route_name = ""
  route_grade = ""
end

result_span =
  case rec.result
  when "Onsight"
    "primary"
  when "Flash"
    "info"
  when "Send"
    "success"
  when "Project"
    "default"
  end
%>
                  <div class="route-grade-result"><p><%= "#{route_name} (#{route_grade})" %><span><%= rec.result %></span></p></div>
                  <div class="area"><p><%= "#{rec.rock.region.name} / #{rec.rock.name} / #{area_name}" %></p></div>
                  <div class="actions-favs">
                      <button class="btn btn-link"><span class="glyphicon glyphicon-star"></span></button>
                      <button class="btn btn-link"><span class="glyphicon glyphicon-pencil"></span></button>
                  </div>
                  <div class="desc"><p class="text_overflow"><%= rec.memo %></p>
                  </div>
                  <div class="comms">8件のコメント</div>
                </div>
              </div>
            </div>
          </td></tr>
          <% end %>
        </tbody>
      </table>

  <div class="col-md-12 col-xs-12">
    <%= paginate @records %>
  </div>
</div>

app/views/records/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>New record</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/records/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3><%= "#{@record.route.name} (#{@record.route.grade})" %></h3>

  </div>
  <div class="panel-body">
    <%= "#{@record.rock.name} / #{@record.area.name}" %>
    <p><%= @record.day %></p>
    <p><%= @record.result %></p>
    <p><%= @record.memo %></p>
  </div>
</div>

<p>
<%
begin
if @record.user_id == current_user.id
%>
<%= link_to 'Edit', edit_record_path(@record.id), class: 'btn btn-primary' %>
<% end %>
<%
rescue
end
%>
<%= link_to 'Back', records_path, class: 'btn btn-default' %>
</p>