config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/converter'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'records#index'

  resources :regions do
    resources :rocks do
      resources :zones do
        resources :areas do
          resources :routes
        end
      end
    end
  end

  resources :regions, only: :index do
    collection { post :import }
  end

  resources :rocks, only: :index do
    collection { post :import }
  end

  resources :zones, only: :index do
    collection { post :import }
  end

  resources :areas, only: :index do
    collection { post :import }
  end

  resources :records do
    collection do
      get :rocks_select
      get :areas_select
      get :routes_select
    end
  end

  resources :routes do
    collection do
      get :areas_select
    end
  end

  resources :routes, only: :index do
    collection { post :import }
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :records
  resources :users
  resources :rocks
  resources :areas
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  get '/signup' => 'users#new'

end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :rocks

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      region = find_by(id: row["id"]) || new
      region.attributes = row.to_hash.slice(*updatable_attributes)
      region.save!
    end
  end

  def self.updatable_attributes
    ["name", "able"]
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    #if current_user.admin?
      @regions = Region.search(params[:search]).where(able: true)
    #else
      #redirect_to root_url
    #end
  end

  def show
    @region = Region.includes(rocks: [areas: [:routes]]).find(params[:id])
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
  end

  def import
    Region.import(params[:file])
    redirect_to regions_path, notice: "Added regions"
  end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_region.html.erb
<tr>
  <td class="region" id="region_<%= region.id %>"><%= region.name %></td>
</tr>

app/views/regions/_search.html.erb
<div class="row">

  <h2>New Reocrd</h2>
  <h3>Search Routes</h3>

</div>

<div class="row region_list">
  <% @regions = Region.search(params[:search_region]).where(able: true) %>
  <table class="table table-hover regions">
  <%= render @regions %>
  </table>
</div>

<div class="row rock_list" style="display: none;">
  <% @rocks = Rock.all %>
  <table class="table table-hover rocks">
    <tr class="active" id="back_to_region"><td colspan="3"><span class="glyphicon glyphicon-chevron-left"></span>back</td></tr>
    <%= render @rocks %>
  </table>
</div>

<div class="row area_list" style="display: none;">
  <% @areas = Area.all %>
  <table class="table table-hover areas">
    <tr class="active" id="back_to_rock"><td colspan="3"><span class="glyphicon glyphicon-chevron-left"></span>back</td></tr>
    <%= render @areas %>
  </table>
</div>

<div class="row route_list" style="display: none;">
  <% @routes = Route.all %>
  <table class="table table-hover routes">
    <tr class="active" id="back_to_area"><td colspan="3"><span class="glyphicon glyphicon-chevron-left"></span>back</td></tr>
    <%= render @routes %>
  </table>
</div>

app/views/regions/index.html.erb
<h1>Region Master</h1>

<% if current_user.admin? %>
  <%= form_tag import_regions_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import" %>
  <% end %>
<% end %>

<ul>
  <% @regions.each do |region| %>
    <li><%= link_to region.name, region_path(region.id) %></li>
  <% end %>
</ul>

app/views/regions/show.html.erb
<h1><%= @region.name %></h1>

  <% if current_user.admin? %>
  <div class="row">
    <p><%= link_to 'Add rock', new_rock_path(:region_id => @region.id), class: 'btn btn-primary btn-sm' %></p>
  </div>
  <% end %>

  <ul class="list-group">
    <% @region.rocks.each do |rock| %>
    <li class="list-group-item list-group-item-info">
      <div class="row">
        <div class="col-md-10"><%= rock.name %></div>
        <% if current_user.admin? %>
        <div class="col-md-1"><%= link_to 'Add area', new_area_path(:rock_id => rock.id, :region_id => rock.region_id), class: 'btn btn-primary btn-sm' %></div>
        <% end %>
      </div>
    </li>
    <ul class="list-group">
    <% rock.areas.each do |area| %>
      <li class="list-group-item list-group-item-warning head_area" id="head_area_<%= area.id %>">
        <div class="row">
          <div class="col-md-9 col-md-offset-1"><%= area.name %></div>
          <% if current_user.admin? %>
          <div class="col-md-1"><%= link_to 'Add route', new_route_path(:area_id => area.id, :region_id => area.rock.region_id), class: 'btn btn-primary btn-sm' %></div>
          <% end %>
        </div>
      </li>
      <ul class="list-group">
        <% area.routes.each do |route| %>
          <li class="list-group-item bottom_route_<%= route.area_id %>">
            <div class="row">
              <div class="col-md-offset-2"><%= "#{route.name}(#{route.grade})" %></div>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
    </ul>
    <% end %>
  </ul>