config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/converter'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'records#index'

  resources :regions do
    resources :rocks do
      resources :zones do
        resources :areas do
          resources :routes
        end
      end
    end
  end

  resources :regions, only: :index do
    collection { post :import }
  end

  resources :rocks, only: :index do
    collection { post :import }
  end

  resources :zones, only: :index do
    collection { post :import }
  end

  resources :areas, only: :index do
    collection { post :import }
  end

  resources :records do
    collection do
      get :rocks_select
      get :areas_select
      get :routes_select
    end
  end

  resources :routes do
    collection do
      get :areas_select
    end
  end

  resources :routes, only: :index do
    collection { post :import }
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :records
  resources :users
  resources :rocks
  resources :areas
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  get '/signup' => 'users#new'

end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Gamba! Share your records and climbing information!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= favicon_link_tag('favicon.ico') %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.1.0/intro.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.1.0/introjs.min.css" rel="stylesheet" type="text/css">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
</head>

<body>
  <div class="container main-container">
    <nav class="navbar navbar-dark bg-dark fixed-top head-navi">
      <div class="container">

        <div class="navbar-header mx-auto logo-box">
          <%= link_to image_tag("logo.png", width: 220), root_url, id: "logo", class: "navbar-brand" %>
        </div>

      </div>
    </nav>

    <div class="row">
      <div class="col-12 main_contents">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>

  <nav class="navbar navbar-expand-lg fixed-bottom navbar-dark bg-dark bottom-navi">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto w-100 nav-justified">
        <li class="nav-item">
          <%= link_to records_path, class: "nav-link", data: { no_turbolink: true } do %>
            <i class="fas fa-home fa-lg"></i>
          <% end %>
        </li>
        <% if current_user %>
        <li class="nav-item">
          <%= link_to "", class: "nav-link" do %>
            <i class="fas fa-search fa-lg"></i>
          <% end %>
        </li>
        <% end %>

        <% if logged_in? %>
        <li class="nav-item">
          <%= link_to new_record_path, class: "nav-link" do %>
            <i class="fas fa-plus-square fa-lg"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "", class: "nav-link" do %>
            <i class="far fa-bell fa-lg"></i>
          <% end %>
        </li>
          <div class="btn-group dropup">
            <%= link_to current_user, class: "nav-link" do %>
              <i class="far fa-user fa-lg"></i>
            <% end %>
          </div>

        <% else %>
          <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div>
  <%= debug(request.path_info) if Rails.env.development? %>
  <%= debug(params) if Rails.env.development? %>
<%
=begin
%>
  <%= debug(@user) if Rails.env.development? && request.path_info == users_path %>
  <%= debug(@records) if Rails.env.development? %>
  <%= debug(@record) if Rails.env.development? && request.path_info == records_path %>
  <%= debug(@grades) if Rails.env.development? && request.path_info == users_path %>
  <%= debug(current_user) if Rails.env.development? %>
<%
=end
%>
  </div>

</body>
</html>